services:
  mysql:
    image: mysql:8.0
    container_name: taskapi-mysql
    environment:
      MYSQL_DATABASE: taskapi_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - taskapi-data:/var/lib/mysql

volumes:
  taskapi-data:
